name: Run Colab Notebook Daily

on:
  schedule:
    # Runs daily at 9 AM IST (03:30 UTC)
    - cron: "30 3 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  run_colab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Execute Colab Notebook Trigger
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python run_colab.py
